-- Postgres alter script (only run first time! may overwrite things...)
-- tree-based hierarchical representation of directory structure where files live

-- https://dba.stackexchange.com/questions/226471/hierarchical-tree-data-which-type-of-database-to-use-design

\connect photodb;

CREATE TABLE files (
    file_id        int   PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    orig_name      text,
    sha3           text  UNIQUE, -- sha3-512() (look into this)
    mime           text,
    bs             int
);
INSERT INTO files (file_id, orig_name, sha3, mime, bs) VALUES
(1, 'dongs.jpg', 'd9be28047e605af3ff9a4b4013e0e05b47a1d6774c3beae9a1038da5bcc9b37e890dd42c1c7cba4cbf7ba5e5c55b104fba5944bfe7d9dbc491d14171da5bdd0b', 'image/jpg', 50042 );

CREATE TABLE virtual_directories (
    vd_id         int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    parent_vd_id  int REFERENCES virtual_directories,
    file_id       int REFERENCES files,
    name          text,
    CHECK ( file_id IS NOT NULL AND parent_vd_id IS NOT NULL or name IS NOT NULL )
);
INSERT INTO virtual_directories ( vd_id, parent_vd_id, file_id, name ) VALUES
  ( 1, null, null, '/'        ), -- root
  ( 2, 1,    null, 'pictures' ),
  ( 3, 2,    1,    'woot.jpg' );